'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BananaSerial.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property BreadBoard_16x1_Horizontal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BreadBoard 16x1 Horizontal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BreadBoard_8x1_Vertical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BreadBoard 8x1 Vertical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property breadboard_top_32_rows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breadboard top 32 rows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property breadboard_top_32_rows1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breadboard top 32 rows1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property breadboard_top_32_rows11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breadboard top 32 rows11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property breadboard_top_64_rows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breadboard top 64 rows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IC_18_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IC 18 Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IC_20_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IC 20 Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IC_24_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IC 24 Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IC_28_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IC 28 Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IC_32_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IC 32 Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IC_40_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IC 40 Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IC14_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IC14 Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IC16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IC16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IC8_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IC8 Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LED0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LED1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Run() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Run", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property schematic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("schematic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
